### ISSUE TITLE
Kinvey Angular and Webpack

### ISSUE THREAD

**Issue by d0nkeyBOB** [Kinvey/kinvey-angular-lib#1]
Great library but I get a warning from webpack (1.12.9), when I'm building my app.

`WARNING in ./~/kinvey-angular/kinvey.min.js
Critical dependencies:
1:434-441 This seems to be a pre-built javascript file. Though this is possible, it's not recommended. Try to require the original source to get better results.
 @ ./~/kinvey-angular/kinvey.min.js 1:434-441`

Nothing changes when I edit the package.json 'main' filename to the non-min version.

Thanks

**Comment by ThomasConner** [comment]
Thanks @d0nkeyBOB. I have not tried including the library in a Webpack build. Do you mind sharing your Webpack config file?

**Comment by d0nkeyBOB** [comment]
Here is my latest.

[webpack.config.txt](https://github.com/Kinvey/kinvey-angular-lib/files/112942/webpack.config.txt)

**Comment by ThomasConner** [comment]
@d0nkeyBOB can you share your project by chance so I can try it locally?

**Comment by d0nkeyBOB** [comment]
I can't because of company security but I could create a mock app with the same setup. It's just a basic angular app with webpack and gulp.

**Comment by ThomasConner** [comment]
If you wouldn't mind doing that I would appreciate it. Just put the link to the Github repo in here. Thanks!

**Comment by d0nkeyBOB** [comment]
Here --> [https://github.com/d0nkeyBOB/testWebpack](https://github.com/d0nkeyBOB/testWebpack)

**Comment by ThomasConner** [comment]
I was able to reproduce the issue. We build I library with browserify which is causing the issue you are experiencing. I am going to look into a way we can provide a build that will support webpack and non-webpack environments.

**Comment by d0nkeyBOB** [comment]
+1 Thanks for looking into it!

**Comment by R0muald** [comment]
+1

**Comment by ThomasConner** [comment]
I have fixed this issue with the latest beta release (3.0.0-beta.5). We are using the [Request](https://github.com/request/request) module with our library. In order to use the library in a webpack build please reference issue [#1529](https://github.com/request/request/issues/1529) to fix any errors caused by using the request module.
